[project]
name = "airbyte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "airbyte-cdk[dev]>=6.54.7",
]

[dependency-groups]
dev = [
    "poethepoet>=0.34.0",
]
